class ValidError(Exception):
    pass


class RepoError(Exception):
    pass

class BackToMain(Exception):
    pass